---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

helmCharts:
- name: prometheus
  releaseName: prometheus
  version: 25.1.0
  repo: https://prometheus-community.github.io/helm-charts
