---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmGlobals:
  chartHome: "../../helm-charts"

helmCharts:
- name: argocd-app
  valuesInline:
    name: argocd
- name: argocd-app
  valuesInline:
    name: prometheus
- name: argocd-app
  valuesInline:
    name: falco