---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  description: infrastructure stuff

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    #- "ssh://git@github.com/masondenney/mdenney-config.git"
    - "https://github.com/masondenney/mdenney-config"
    - "https://kubernetes-charts.storage.googleapis.com"
    - "https://charts.helm.sh/stable"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  # Deny most cluster-scoped resources from being created, except for:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: gateway.networking.k8s.io
      kind: GatewayClass
    - group: networking.k8s.io
      kind: IngressClass
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: policy
      kind: PodSecurityPolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration

  # Allow all namespaced-scoped resources to be created, except for:
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
