---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - includeCRDs: true
    name: argo-cd
    namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: helm-values.yaml
    version: 6.4.0

namespace: argocd
